---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.9
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Manila
    volumes:
      - ./config:/config
      - /media/choco/data:/data
    ports:
      - 8989:8989